#!/usr/bin/tclsh

lappend auto_path .

package require ::midi
package require ::rawtuning

# set dict [::rawtuning::get-dict 10 stick]
set dict [::rawtuning::get-dict 8 stick]
foreach key [dict keys $dict] {
    puts [::rawtuning::to-preset $key [dict get $dict $key]]
}

